### PR TITLE
Updated uap-core for newer yaml definitions

### PR DESCRIPTION
**Pull request by kraklin**
Hi,

We are using UAParser in our code but we were unable to parse Outlook 2016 correctly. I found out that the uap-core has not been updated for a while so I updated the submodule to get new definition yaml files.

### CODE REVIEW

**Comment by kraklin** [comment]
Also building it with travis default settings means build it with ruby so check cannot be green at all :)

**Comment by enemaerke** [comment]
@kraklin Yeah, I haven't updated that in a while :)

If you need a quick fix, there should be an overload that accepts a yaml file directly rather than pulling from the embedded resource...

Not sure I follow the travis default settings comment, could you help me out there?

**Comment by kraklin** [comment]
:) after I

**Comment by kraklin** [comment]
:) after I created the merge request, Travis has been run automaticaly and failed because of no .travis.yml was found. In the case no .travis.yml is found it runs with default configuration - ruby. You can see the result here: https://travis-ci.org/ua-parser/uap-csharp/builds/199996505

**Comment by kraklin** [comment]
Well I tried the updated binary localy (just copied from /Release to our package folder) and there are some regression problems in our test, so the upgrade is not urgent yet :D

**Comment by enemaerke** [comment]
I have appvevyor tests running of my local fork, so I'll take a look at it as soon as I have a bit of spare time

**Comment by benabbon** [comment]
Any updates on this?

**Comment by kraklin** [comment]
@benabbon I just copied the yaml definitions file and loading it from Parser factory. It works for now ;)

**Comment by benabbon** [comment]
@kraklin I was hoping not to do that and stick with the official nugget itself. But I guess I'll switch to the yaml as well

**Comment by enemaerke** [comment]
Sorry for the loooooong wait. I've just updated the official NuGet and will close this PR.

**Pull request closed without merging**
