### PR TITLE
Support for .NET Core

### PR DESCRIPTION
**Pull request by christianhxc**
Changed projects so they can be ready for .NET Core

Please review changes made and make suggestions, I'm not really sure if I did this right in order to keep supporting .NET Framework 4. I'm planning to use this code in other project and I would like to remove the source code and use the nuget reference instead.

### CODE REVIEW

**Comment by christianhxc** [comment]
Not sure also how to update the CI build :(

**Comment by ronaldscott** [comment]
@sorenenemaerke, @raboof, what are the odds of this PR getting merged?

**Comment by enemaerke** [comment]
Oh, haven't looked at this in a long while and is pretty swamped with non-code stuff, so I can't make any commitment to this right now. Sorry

**Comment by flo8** [comment]
Hi! Congrats with the great work, would love to see this PR getting merged as well :)

**Comment by christianhxc** [comment]
I think that it might worth waiting for .NET Standard 2

**Comment by enemaerke** [comment]
Hi there.

I just ported the library to netstandard1.0 and netstandard1.3. It's uploaded to NuGet as version 3.0. I'll close this PR but feel free to open an issue if there are additional things to address

**Pull request closed without merging**
